vilega/O365Troubleshooters

O365Troubleshooters.psm1

implemented Read-IntFromConsole function
it will loop for 3 attempts to enter a valid number.
If all 3 attempts are failed, it will Write-Log and send the user to O365Troubleshooters Main Menu
This will resolve Enhancement Issue #77

implemented Read-IntFromConsole

---

O365Troubleshooters.psd1

Fixed tags from manifest. Space is not allowed for #86

Fixed tags from manifest. Space is not allowed

---

O365Troubleshooters.psm1

disconnect azureAD and azureADPreview

---

ActionPlans/Export-ExoQuarantineMessages.ps1

Sanitized Export-ExoQuarantineMessage code.
Removed refferences to Disconnect-All
Implemented Read-Key instead of Read-host
This will close Issue #79

Align Export-ExoQuarantineMessage

---

ActionPlans/Start-AzureADAuditSignInLogSearch.ps1
ActionPlans/Start-CompromisedInvestigation.ps1
ActionPlans/Start-ExchangeOnlineAuditSearch.ps1
ActionPlans/Start-Office365Relay.ps1
O365Troubleshooters.psm1

Modified ETR AP to export Array of Suspicious Rules.
Implemented JournalRule Array collection.

Reviewed ETR and JournalRule

---

ActionPlans/Connect-ServicesWithTokens.ps1
O365Troubleshooters.psm1

Get-Token function to connect to services
Azure, AIP, EXO

Get-Token function to connect to services

---

ActionPlans/Start-CompromisedInvestigation.ps1
O365Troubleshooters.psd1
O365Troubleshooters.psm1

Connect-ServicesWithTokens.ps1
load Connect-ServicesWithTokens.ps1 in Set-GlobalVariables

load Connect-ServicesWithTokens in Set-GlobalVariables

---

ActionPlans/Start-CompromisedInvestigation.ps1

fix typo in GlobalAdminsSignInAuditLogsNotification

fix typo in GlobalAdminsSignInAuditLogsNotification

---

ActionPlans/Start-AzureADAuditSignInLogSearch.ps1

fixing filter used for query within the standalone tool
Fixes Issue #109

Start-AzureADAuditSignInLogSearch - fixing AP Filter

---

O365Troubleshooters.psm1

This is in regards to #118 and #120 
Closes #120

Corrected minor BUG related to Section title and its color

---

ActionPlans/Start-UnifiedAuditLogSearch.ps1

Correcting the part of code that checks logs for a specific user

---

ActionPlans/Start-MailboxMigrationAnalyzer.ps1
O365Troubleshooters.psd1
O365Troubleshooters.psm1

Mailbox migration analyzer - Phase 1

---

ActionPlans/Start-MailboxMigrationAnalyzer.ps1

Solve BUG129

---

O365Troubleshooters.psm1

Resolved BUG131

---

O365Troubleshooters.psd1

publish O365Troubleshooters 2020 August ver.: 2.0.0.14

update manifest for 2.0.0.14

---

ActionPlans/Start-MailboxMigrationAnalyzer.ps1
O365Troubleshooters.psm1

I've created a new function for saving the output to an HMTL report.
Closes #135

I've created a new function for saving the output to an HMTL report.

---

ActionPlans/Start-Office365Relay.ps1

Initial implementation for HTML report for Office365Relay AP.
cosmetics will be addressed in a future pull request.

Implementing HTML Report for Office365Relay

---

O365Troubleshooters.psm1

Improving Get-ValidEmailAddress function to:
-provide feedback to user in Console that the Email Address does not match validation Regex.
-use write-log to write down invalid Email Address to check Regex if needed for undesired match failures.

improving end user experience and logging for Get-ValidEmailAddress

---

ActionPlans/Start-DecodeSafeLinksURL.ps1

updated regex to avoid false positive match on other redirect services.

Safe Links Decode URL - updated regex

---

ActionPlans/Start-CompromisedInvestigation.ps1
O365Troubleshooters.psm1

Implemented generalized HTML Report from main O365Troubleshooters Module.
A lot of code optimization that should improve performance also managed along the way.

Compromised Investigation - Implement HTML Report

---

O365Troubleshooters.psd1

update the manifest file
close #151

update the manifest file

---

ActionPlans/Start-PublicFolderTroubleshooter.ps1
O365Troubleshooters.psd1

- Fix connectivity issues when MFA is using old module
- Fix Public Folder action plan
- Update manifest file
closes #159 
closes #160

Fix Public Folder action plan

---

O365Troubleshooters.psd1
O365Troubleshooters.psm1

Improved EXO and SCC connection

---

ActionPlans/Start-DlToO365GroupUpgradeChecks.ps1
O365Troubleshooters.psd1

Update DL owner recipient type details condition to support only MBX & MEU

Update DL owner recipient type details condition on DLupgradechecker diag 

---

ActionPlans/Start-DecodeSafeLinksURL.ps1
O365Troubleshooters.psm1

- improve error handling
- improve documentation
- improve naming convention
- generate HTML report
- work also on #167

DecodeSafeLinksURL

---

ActionPlans/Get-X500FromImceaexNdr.ps1
ActionPlans/Start-DecodeSafeLinksURL.ps1
O365Troubleshooters.psm1

close #201 
Build and re-write:
- help
- more descriptive comments
- export to HTML the results
- transform more than one Imceaex NDR if needed
- better handle errors

Re-write Get-X500FromImceaexNDR
